---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
# wellness_survey_report

The goal of WFU_Wellbeing_Assessment_Reports_2018_external is to generate reports of the descriptive statistics for the 2018 Wellbeing Assessment survey. 

This code will NOT run automatically for you because it pulls the data directly from Qualtrics. For security reasons, we cannot release the API token that pulls the data and generates the report. 

You are, however, more than welcome to adapt this code for your own use.

The code can all be run from the Rmd file "2018_wb_report". The rest of the documents are supporting syntax or source files. 

The packages you will need are listed at the top of "charts_and_tables." In addition to those packages, you will need knitr. 

One of the packages--datademon--installs from our repository titled "Wellbeing_tools." We are not the author of that package; it was authored by Michael DeWitt, Wake's Data Scientist in the Institutional Research office. 

For those of you familiar with R, you'll see that our code is very much a work in progress. Please be patient as we learn R and more efficient reporting methods. If you have any fixes, we'd love to hear about them!

